// Omise error list
// Authentication part
export const ERROR_CODE_OMISE_ORIGINAL_AUTHENTICATION_FAILURE: string =
  'authentication_failure';
export const ERROR_CODE_OMISE_RETURN_AUTHENTICATION_FAILURE: string =
  'ERROR_CODE_OMISE_RETURN_AUTHENTICATION_FAILURE';

export const ERROR_CODE_OMISE_ORIGINAL_INVALID_AMOUNT: string =
  'invalid_amount';
export const ERROR_CODE_OMISE_RETURN_INVALID_AMOUNT: string =
  'ERROR_CODE_OMISE_RETURN_INVALID_AMOUNT';

export const ERROR_CODE_OMISE_ORIGINAL_INSUFFICIENT_FUND: string =
  'insufficient_fund';
export const ERROR_CODE_OMISE_RETURN_INSUFFICIENT_FUND: string =
  'ERROR_CODE_OMISE_RETURN_INSUFFICIENT_FUND';

export const ERROR_CODE_OMISE_ORIGINAL_STOLEN_CARD: string =
  'stolen_or_lost_card';
export const ERROR_CODE_OMISE_RETURN_STOLEN_CARD: string =
  'ERROR_CODE_OMISE_RETURNL_STOLEN_CARD';

export const ERROR_CODE_OMISE_ORIGINAL_FAIL_PROCESSING: string =
  'failed_processing';
export const ERROR_CODE_OMISE_RETURN_FAIL_PROCESSING: string =
  'ERROR_CODE_OMISE_RETURN_FAIL_PROCESSING';

export const ERROR_CODE_OMISE_ORIGINAL_PAYMENT_REJECTED: string =
  'payment_rejected';
export const ERROR_CODE_OMISE_RETURN_PAYMENT_REJECTED: string =
  'ERROR_CODE_OMISE_RETURN_PAYMENT_REJECTED';

export const ERROR_CODE_OMISE_ORIGINAL_INVALID_SECURITY_CODE: string =
  'invalid_security_code';
export const ERROR_CODE_OMISE_RETURN_INVALID_SECURITY_CODE: string =
  'ERROR_CODE_OMISE_RETURN_INVALID_SECURITY_CODE';

export const ERROR_CODE_OMISE_ORIGINAL_FAILED_FRAUD_CHECK: string =
  'failed_fraud_check';
export const ERROR_CODE_OMISE_RETURN_FAILED_FRAUD_CHECK: string =
  'ERROR_CODE_OMISE_RETURN_FAIED_FRAUD_CHECK';

export const ERROR_CODE_OMISE_ORIGINAL_INVALID_ACCOUNT_NUMBER: string =
  'invalid_account_number';
export const ERROR_CODE_OMISE_RETURN_INVALID_ACCOUNT_NUMBER: string =
  'ERROR_CODE_OMISE_RETURNL_INVALID_ACCOUNT_NUMBER';

export const ERROR_CODE_OMISE_ORIGINAL_INVALID_CHARGE: string =
  'invalid_charge';
export const ERROR_CODE_OMISE_RETURN_INVALID_CHARGE: string =
  'ERROR_CODE_OMISE_RETURN_INVALID_CHARGE';

  export const ERROR_CODE_OMISE_ORIGINAL_USED_TOKEN: string =
  'used_token';
export const ERROR_CODE_OMISE_RETURN_USED_TOKEN: string =
  'ERROR_CODE_OMISE_RETURN_USED_TOKEN';

const createOmiseMapError = (): Map<string, string> => {
  const returnMap = new Map<string, string>();
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_AUTHENTICATION_FAILURE,
    ERROR_CODE_OMISE_RETURN_AUTHENTICATION_FAILURE,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_INVALID_AMOUNT,
    ERROR_CODE_OMISE_RETURN_INVALID_AMOUNT,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_INSUFFICIENT_FUND,
    ERROR_CODE_OMISE_RETURN_INSUFFICIENT_FUND,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_STOLEN_CARD,
    ERROR_CODE_OMISE_RETURN_STOLEN_CARD,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_FAIL_PROCESSING,
    ERROR_CODE_OMISE_RETURN_FAIL_PROCESSING,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_PAYMENT_REJECTED,
    ERROR_CODE_OMISE_RETURN_PAYMENT_REJECTED,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_INVALID_SECURITY_CODE,
    ERROR_CODE_OMISE_RETURN_INVALID_SECURITY_CODE,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_FAILED_FRAUD_CHECK,
    ERROR_CODE_OMISE_RETURN_FAILED_FRAUD_CHECK,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_INVALID_ACCOUNT_NUMBER,
    ERROR_CODE_OMISE_RETURN_INVALID_ACCOUNT_NUMBER,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_INVALID_CHARGE,
    ERROR_CODE_OMISE_RETURN_INVALID_CHARGE,
  );
  returnMap.set(
    ERROR_CODE_OMISE_ORIGINAL_USED_TOKEN,
    ERROR_CODE_OMISE_RETURN_USED_TOKEN,
  );
  return returnMap;
};
export const omiseErrorMap: Map<string, string> = createOmiseMapError();
